require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'config/environments/**/*'

Layout/LineLength:
  Exclude:
    - 'db/seeds.rb'

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/users/passwords_controller.rb'
Metrics/MethodLength:
  Exclude:
    - 'app/lib/collection_properties.rb'
    - 'app/controllers/users/passwords_controller.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'

# Rails-specific configuration
Rails:
  Enabled: true

# Add other configurations and customizations as needed
